IdentityLearning/Models/ViewModels/CreateRoleViewModel.cs
using IdentityLearning.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace IdentityLearning.Models.ViewModels
{
    [CheckXss]
    public class CreateRoleViewModel
    {
        [Required(ErrorMessage ="لطفا نام نقش را وارد کنید")]
        [DisplayName("نام نقش")]
        [RegularExpression("[a-zA-Z]+",ErrorMessage ="لطفا فقط از حروف انگلیسی برای نام نقش استفاده کنید")]
        public string RoleName { get; set; }
        public List<SelectListItem> PermissionIn { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> PermissionOut { get; set; } = new List<SelectListItem>();

    }
}

IdentityLearning/Controllers/RoleManagerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using IdentityLearning.Models;
using IdentityLearning.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using IdentityLearning.Infrastructure;
using SharedServices.Models.IdentityModels;

namespace IdentityLearning.Controllers
{


    [Authorize(Policy = nameof(PersmissionsEnum.BasePermission))]
    public class RoleManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleManagerController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        [Authorize(Policy = nameof(PersmissionsEnum.RoleView))]
        [MarkedToNavBar("نمایش نقش ها")]
        public IActionResult ShowRoles()
        {
            var roles = roleManager.Roles.Where(c=>c.Name!= "SuperAdmin").ToList();
            return View(roles);
        }

        [HttpGet]
        [Authorize(Policy = nameof(PersmissionsEnum.CreateRole))]
        [MarkedToNavBar("ایجاد یک نقش")]
        public IActionResult CreateRole()
        {
            ViewBag.permissions = ClaimToPermission.GetAllClaims();
            CreateRoleViewModel vm = new CreateRoleViewModel();
            foreach (var item in ClaimToPermission.GetAllClaims())
            {
                vm.PermissionOut.Add(new SelectListItem()
                {
                    Selected = false,
                    Text = item.Value,
                    Value = item.Key
                });
            }
            return View(vm);
        }


        [Authorize(Policy = nameof(PersmissionsEnum.CreateRole))]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel role)
        {
            if (ModelState.IsValid)
            {
                if (await roleManager.RoleExistsAsync(role.RoleName))
                {
                    ModelState.AddModelError("RoleIsExists", "نقش با این نام در سیستم موجود است.لطفا نام دیگری را امتحان کنید");
                    ViewBag.UnValid = true;
                    return View(role);

                }
                var CreateResult = await roleManager.CreateAsync(new IdentityRole()
                {
                    Name = role.RoleName
                });
                if (CreateResult.Succeeded)
                {
                    var RoleEntity = await roleManager.FindByNameAsync(role.RoleName);
                    foreach (var item in role.PermissionIn)
                    {
                        if (Enum.IsDefined(typeof(PersmissionsEnum), item.Value))
                        {
                            if (item.Selected == false)
                                await roleManager.RemoveClaimAsync(RoleEntity, new Claim("AccessLevel", item.Value));
                        }
                    }

                    foreach (var item in role.PermissionOut)
                    {
                        if (Enum.IsDefined(typeof(PersmissionsEnum), item.Value))
                        {
                            if (item.Selected == true)
                                await roleManager.AddClaimAsync(RoleEntity, new Claim("AccessLevel", item.Value));
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("ErrorInCreateRole", "ایجاد نقش با مشکل مواجه شده است");
                    ViewBag.UnValid = true;
                    return View(role);
                }

                return RedirectToAction("ShowRoles");
            }
            ViewBag.UnValid = true;
            return View(role);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = nameof(PersmissionsEnum.DeleteRole))]
        public async Task<IActionResult> DeleteRole(string Id)
        {
            Id = CheckXss.CheckIt(Id);
            var Role = await roleManager.FindByIdAsync(Id);
            if (Role != null)
            {
                var DeleteResult = await roleManager.DeleteAsync(Role);

            }

            return RedirectToAction("ShowRoles");
        }

        [HttpGet]
        [Authorize(Policy = nameof(PersmissionsEnum.AccessLevelRole))]
        public async Task<IActionResult> AccessLevelRole(string Id)
        {
            Id = CheckXss.CheckIt(Id);
            if (TempData["success"] != null)
            {
                ViewBag.Success = true;
                TempData.Remove("success");
            }
                

            var Role = await roleManager.FindByIdAsync(Id);
            var RoleClaims = await roleManager.GetClaimsAsync(Role);


            var permissions = ClaimToPermission.GetAllClaims();
            CreateRoleViewModel vm = new CreateRoleViewModel();
            vm.RoleName = Role.Name;
            foreach (var item in RoleClaims)
            {
                var PersianName = permissions.FirstOrDefault(x => x.Key == item.Value).Value;
                if (PersianName == null || PersianName == "")
                    PersianName = item.Value;
                vm.PermissionIn.Add(new SelectListItem()
                {
                    Selected = true,
                    Text = PersianName,
                    Value = item.Value
                });
            }
            var ExceptsPermissions = permissions.Where(x => RoleClaims.Any(y => y.Value == x.Key) == false).ToList();

            foreach (var item in ExceptsPermissions)
            {
                vm.PermissionOut.Add(new SelectListItem()
                {
                    Selected = false,
                    Text = item.Value,
                    Value = item.Key
                });
            }

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = nameof(PersmissionsEnum.AccessLevelRole))]
        public async Task<IActionResult> AccessLevelRole(CreateRoleViewModel Role)
        {
            if (ModelState.IsValid)
            {
                if (!await roleManager.RoleExistsAsync(Role.RoleName))
                {
                    ModelState.AddModelError("RoleIsNotExists", "نقشی با این نام در سیستم موجود نیست");
                    ViewBag.UnValid = true;
                    return View(Role);

                }


                var RoleEntity = await roleManager.FindByNameAsync(Role.RoleName);
                if (RoleEntity != null)
                {

                    foreach (var item in Role.PermissionIn)
                    {
                        if (Enum.IsDefined(typeof(PersmissionsEnum), item.Value))
                        {
                            if (item.Selected == false)
                            {
                                await roleManager.RemoveClaimAsync(RoleEntity, new Claim("AccessLevel", item.Value));

                            }
                        }
                    }

                    foreach (var item in Role.PermissionOut)
                    {
                        if (Enum.IsDefined(typeof(PersmissionsEnum), item.Value))
                        {
                            if (item.Selected == true)
                            {
                                await roleManager.AddClaimAsync(RoleEntity, new Claim("AccessLevel", item.Value));

                            }
                        }
                    }

                }
                else
                {
                    ModelState.AddModelError("ErrorInCreateRole", "ایجاد نقش با مشکل مواجه شده است");
                    ViewBag.UnValid = true;

                    return View(Role);
                }
                TempData["Success"] = true;

                return RedirectToAction("AccessLevelRole", new[] { RoleEntity.Id });
            }
            ViewBag.UnValid = true;
            return View(Role);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateRole(string Id)
        {
            Id = CheckXss.CheckIt(Id);
            var RoleEntity = await roleManager.FindByIdAsync(Id);
            if (RoleEntity == null)
                return NotFound();
            RoleUpdateViewModel vm = new RoleUpdateViewModel()
            {
                OldRoleName = RoleEntity.Name,
                RoleId = Id
            };
            TempData["RoleUpdatename"] = RoleEntity.Name;
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateRole([Bind("RoleId , NewRoleName")]RoleUpdateViewModel vm)
        {
            if (ModelState.IsValid)
            {
                if (await roleManager.RoleExistsAsync(vm.NewRoleName))
                {
                    ModelState.AddModelError("Name Is Exists", "نقشی با این نام در سیستم وجود دارد.نام دیگری را انتخاب کنید");

                    vm.OldRoleName = TempData["RoleUpdatename"] as string ?? "";
                    return View(vm);
                }
                var RoleEntity = await roleManager.FindByIdAsync(vm.RoleId);
                if (RoleEntity == null)
                {
                    ModelState.AddModelError("Id Is False", "چنین نقشی در سیستم موجود نیست");

                    vm.OldRoleName = TempData["RoleUpdatename"] as string ?? "";
                    return View(vm);
                }
                RoleEntity.Name = vm.NewRoleName;
                await roleManager.UpdateAsync(RoleEntity);
                return RedirectToAction(nameof(ShowRoles));
            }
            vm.OldRoleName = TempData["RoleUpdatename"] as string ?? "";
            return View(vm);
        }
    }
}

IdentityLearning/Views/RoleManager/AccessLevelRole.cshtml
@model CreateRoleViewModel
@{
    ViewData["Title"] = "AccessLevelRole";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}



<h3 style="margin-bottom:20px;text-align:right;direction:rtl">سطح دسترسی نقش @Model.RoleName</h3>

<div class="row gutters" style="font-size:16px;">
    @if (ViewBag.UnValid != null)
    {
        <div asp-validation-summary="All"
             class="alert alert-danger" style="direction:rtl;text-align:right;"></div>
    }

    @if (ViewBag.Success != null)
    {
        <div class="alert alert-success col-12"
             style="direction:rtl;text-align:right;">
            <p>
                عملیات با موفقیت انجام شد
            </p>
        </div>
    }


    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="table-container">
            <div class="table-responsive">
                <form class="col-12" asp-action="AccessLevelRole" asp-controller="RoleManager" method="post" asp-antiforgery="true">

                    <input asp-for="RoleName" value="@Model.RoleName" hidden />

                    <table class="table custom-table m-0" style="direction:rtl;text-align:right;">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th>نام وظیفه</th>
                                <th> تخصیص یا عدم تخصیص وظیفه به نقش</th>
                            </tr>
                        </thead>

                        <tbody>
                            @{ int counter = 1;}
                            @for (int i = 0; i < Model.PermissionOut.Count; i++)
                            {
                                <tr>
                                    <th scope="row">@(counter)</th>
                                    <td>@Model.PermissionOut[i].Text</td>
                                    <td>
                                        <input type="checkbox" asp-for="PermissionOut[i].Selected" />
                                        <input type="hidden" asp-for="PermissionOut[i].Value" hidden />
                                        <input type="hidden" asp-for="PermissionOut[i].Text" hidden />
                                    </td>
                                </tr>


                                counter++;

                            }

                            @for (int i = 0; i < Model.PermissionIn.Count; i++)
                            {
                                <tr>
                                    <th scope="row">@counter</th>
                                    <td>@Model.PermissionIn[i].Text</td>
                                    <td>
                                        <input type="checkbox" asp-for="PermissionIn[i].Selected" />
                                        <input type="hidden" asp-for="PermissionIn[i].Value" hidden />
                                        <input type="hidden" asp-for="PermissionIn[i].Text" hidden />
                                    </td>
                                </tr>

                                counter++;

                            }


                        </tbody>
                    </table>

                    <input type="submit" class="btn btn-success" value="ثبت" style="width:100px;;float:right;margin-top:20px;" />
                </form>

            </div>
        </div>
    </div>








    <div class="col-12">
        <a style="float:left;width:130px;" class="btn btn-primary" asp-action="ShowRoles" asp-controller="RoleManager">بازگشت به صفحه قبل</a>

    </div>
</div>

IdentityLearning/Views/RoleManager/CreateRole.cshtml
@model CreateRoleViewModel


@{
    ViewData["Title"] = "CreateRole";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}






<div class="row gutters" style="font-size:16px;">
    <h3 style="margin-bottom:20px;text-align:right;direction:rtl;font-size:16px;">ایجاد نقش جدید</h3>


    @if (ViewBag.UnValid != null)
    {
        <div asp-validation-summary="ModelOnly"
             class="alert alert-danger" style="direction:rtl;text-align:right;"></div>
    }



    <form class="col-12" asp-action="CreateRole" asp-controller="RoleManager" method="post" asp-antiforgery="true">

        <div class="row" style="text-align:right;direction:rtl;margin-bottom:20px;">
            <div class="col-2">
                <label asp-for="RoleName"></label>
            </div>
            <div class="col-5">
                <input class="input-group-text" asp-for="RoleName" style="direction:rtl;text-align:right;" />
                <span asp-validation-for="RoleName" class="validation"></span>
            </div>

        </div>

        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="table-container">
                <div class="table-responsive">
                    <table class="table custom-table m-0" style="direction:rtl;text-align:right;">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th>نام وظیفه</th>
                                <th> تخصیص یا عدم تخصیص وظیفه به نقش</th>
                            </tr>
                        </thead>

                        <tbody>
                            @{ int counter = 1;}
                            @for (int i = 0; i < Model.PermissionOut.Count; i++)
                            {
                                <tr>
                                    <th scope="row">@(counter)</th>
                                    <td>@Model.PermissionOut[i].Text</td>
                                    <td>
                                        <input type="checkbox" asp-for="PermissionOut[i].Selected" />
                                        <input type="hidden" asp-for="PermissionOut[i].Value" hidden />
                                        <input type="hidden" asp-for="PermissionOut[i].Text" hidden />
                                    </td>
                                </tr>


                                counter++;

                            }

                            @for (int i = 0; i < Model.PermissionIn.Count; i++)
                            {
                                <tr>
                                    <th scope="row">@counter</th>
                                    <td>@Model.PermissionIn[i].Text</td>
                                    <td>
                                        <input type="checkbox" asp-for="PermissionIn[i].Selected" />
                                        <input type="hidden" asp-for="PermissionIn[i].Value" hidden />
                                        <input type="hidden" asp-for="PermissionIn[i].Text" hidden />
                                    </td>
                                </tr>

                                counter++;

                            }


                        </tbody>
                    </table>




                </div>
            </div>
        </div>



      
        <input type="submit" class="btn btn-success" value="ثبت" style="width:130px;float:right;margin-top:20px;" />
    </form>

    <div class="col-12">
        <a style="margin-top:20px;float:left;width:140px;" class="btn btn-primary" asp-action="ShowRoles" asp-controller="RoleManager">بازگشت به صفحه قبل</a>

    </div>
   
</div>

IdentityLearning/Views/RoleManager/ShowRoles.cshtml
@model List<IdentityRole>
@{
    ViewData["Title"] = "ShowRoles";
    //Layout = "_layout";
}


<div class="row gutters">

    <div class="col-12" style="direction:rtl;font-size:60px;">
        <a type="submit" style="float:right;margin-bottom:10px;"
           class="btn btn-success" asp-action="CreateRole" asp-controller="RoleManager"> افزودن نقش</a>
    </div>


    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="table-container">
            <div class="table-responsive">
                <table class="table custom-table m-0" style="direction:rtl;font-size:16px;">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">نام نقش</th>
                            <th scope="col">حذف نقش</th>
                            <th scope="col">تغییر نقش</th>
                            <th scope="col">تغییر سطح دسترسی نقش</th>

                        </tr>
                    </thead>
                    @{
                        int counter = 1;
                    }
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@counter</th>
                                <td>@item.Name</td>
                                <td>
                                    <form asp-action="DeleteRole" asp-controller="RoleManager" asp-antiforgery="true"
                                          asp-route-id="@item.Id"
                                          method="post">
                                        <input type="submit" class="btn btn-danger"
                                               value="حذف نقش" />


                                    </form>

                                </td>
                                <td>

                                    <form asp-action="UpdateRole" asp-controller="RoleManager"
                                          asp-route-id="@item.Id"
                                          method="get">
                                        <input type="submit" class="btn btn-info"
                                               value=" تغییر نقش" />


                                    </form>

                                </td>

                                <td>
                                    <form asp-action="AccessLevelRole" asp-controller="RoleManager"
                                          asp-route-id="@item.Id"
                                          method="get">
                                        <input type="submit" class="btn btn-warning"
                                               value="  تغییر سطح دسترسی نقش" />


                                    </form>

                                </td>
                            </tr>

                            counter++;
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>


    
</div>

IdentityLearning/Views/RoleManager/UpdateRole.cshtml
@model RoleUpdateViewModel
@{
    ViewData["Title"] = "UpdateRole";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="card">
        <div class="card-body">

            <div class="row gutters">

                <form class="form-inline col-12" asp-action="UpdateRole" asp-controller="RoleManager"
                      asp-antiforgery="true" method="post"
                      style="direction:rtl;text-align:right;">
                    <div asp-validation-summary="ModelOnly">

                    </div>

                    <input asp-for="RoleId" value="@Model.RoleId" hidden readonly />


                    <div class="col-xl-4 col-lg col-md-6 col-sm-8 col-12">
                        
                            <label style="display:block;text-align:right">نام نقش</label>
                       
                       
                        @*<input type="text" readonly class="form-control-plaintext" id="staticEmail2" value="@Model.OldRoleName">*@
                        <p>@Model.OldRoleName</p>
                    </div>



                    <div class="col-xl-4 col-lg col-md-6 col-sm-8 col-12">

                        <label style="display:block;text-align:right">نام جدید نقش</label>
                        <input type="text" class="form-control" asp-for="NewRoleName" placeholder="نام نقش جدید">
                        <span asp-validation-for="NewRoleName" class="validation"></span>
                    </div>


                    <div class="col-12">
                        <input value="ثبت" style="width:130px;margin-top:30px;" type="submit" class="btn btn-block btn-primary">

                    </div>
                </form>

                <div class="col-12">
                    <a style="float:left;width:130px;" class="btn btn-primary" asp-action="ShowRoles" asp-controller="RoleManager">بازگشت به صفحه قبل</a>

                </div>

               
            </div>
        </div>
    </div>
</div>