IdentityLearning/ViewComponents/NavBarViewComponent.cs
using IdentityLearning.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Reflection;
using IdentityLearning.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace IdentityLearning.ViewComponents
{
    public class TopMenuViewComponent : ViewComponent
    {
        public TopMenuViewComponent()
        {

        }

        public async Task<IViewComponentResult> InvokeAsync()
        {

            var accessLevel = new HashSet<NavBarViewModel>();
            if (!User.Identity.IsAuthenticated)
            {
                return View(new List<IGrouping<string, NavBarViewModel>>());
            }
            var claimsList = HttpContext.User.Claims;
            var assembly = Assembly.GetExecutingAssembly();
            var controllers = assembly.GetTypes().Where(x => x.Name.EndsWith("Controller"));

            foreach (var controller in controllers)
            {
                //controller need authrozie
                if (controller.CustomAttributes.Any(c => c.AttributeType == typeof(AuthorizeAttribute)))
                {
                    bool isControllerAccept = true;
                    object[] controllerAtts = controller.GetCustomAttributes(typeof(AuthorizeAttribute), true);
                    foreach (AuthorizeAttribute att in controllerAtts)
                    {
                        if (object.ReferenceEquals(att.Policy, null))
                            continue;

                        if (!claimsList.Any(c => c.Type == "AccessLevel" &&
                         c.Value == att.Policy))
                        {
                            isControllerAccept = false;
                            break;
                        }

                    }
                    //user authorize for controller
                    if (isControllerAccept)
                    {
                        var methods = controller.GetMethods().Where(m => m.CustomAttributes.Any
                    (z => z.AttributeType == typeof(MarkedToNavBarAttribute))
                    && !m.CustomAttributes.Any(z => z.AttributeType == typeof(HttpPostAttribute))).ToList();




                        foreach (var method in methods)
                        {
                            string persianMathodName = method.GetCustomAttribute<MarkedToNavBarAttribute>().name;
                            //method need authorize
                            if (method.CustomAttributes.Any(m => m.AttributeType == typeof(AuthorizeAttribute)))
                            {
                                bool addToList = true;
                                object[] atts = method.GetCustomAttributes(typeof(AuthorizeAttribute), true);
                                foreach (AuthorizeAttribute att in atts)
                                {
                                    if (object.ReferenceEquals(att.Policy, null))
                                        continue;

                                    if (!claimsList.Any(x => x.Type == "AccessLevel"
                                     && x.Value == att.Policy))
                                    {
                                        addToList = false;
                                        break;
                                    }
                                }
                                if (addToList)
                                    accessLevel.Add(new NavBarViewModel()
                                    {
                                        ActionName = method.Name,
                                        ControllerName = controller.Name.Remove(controller.Name.Length - 10),
                                        PersianAccessLevelName = persianMathodName
                                    });

                            }
                            //method dont need authorize
                            else
                            {

                                accessLevel.Add(new NavBarViewModel()
                                {
                                    ActionName = method.Name,
                                    ControllerName = controller.Name.Remove(controller.Name.Length - 10),
                                    PersianAccessLevelName = persianMathodName
                                });
                            }
                        }

                    }
                }
                //controller dont need authorize
                else
                {
                    //methods should be show in menu
                    var methods = controller.GetMethods().Where(m => m.CustomAttributes.Any
                    (z => z.AttributeType == typeof(MarkedToNavBarAttribute))
                    &&!m.CustomAttributes.Any(z=>z.AttributeType==typeof(HttpPostAttribute))).ToList();

                    foreach (var method in methods)
                    {
                        string persianMathodName = method.GetCustomAttribute<MarkedToNavBarAttribute>().name;
                        //method need authorize
                        if (method.CustomAttributes.Any(m => m.AttributeType == typeof(AuthorizeAttribute)))
                        {
                            bool addToList = true;
                            object[] atts = method.GetCustomAttributes(typeof(AuthorizeAttribute), true);
                            foreach (AuthorizeAttribute att in atts)
                            {
                                if (object.ReferenceEquals(att.Policy, null))
                                    continue;

                                if (!claimsList.Any(x => x.Type == "AccessLevel"
                                 && x.Value == att.Policy))
                                {
                                    addToList = false;
                                    break;
                                }
                            }
                            if (addToList)
                                accessLevel.Add(new NavBarViewModel()
                                {
                                    ActionName = method.Name,
                                    ControllerName = controller.Name,
                                    PersianAccessLevelName = persianMathodName
                                });

                        }
                        //method dont need authorize
                        else
                        {

                            accessLevel.Add(new NavBarViewModel()
                            {
                                ActionName = method.Name,
                                ControllerName = controller.Name.Remove(controller.Name.Length - 10),
                                PersianAccessLevelName = persianMathodName
                            });
                        }
                    }
                }
            }



            //foreach (var item in controllers)
            //{
            //    bool checkControllerPolicy = true;
            //    string persianControllerAccessname = "";
            //    if (item.CustomAttributes.Any(c => c.AttributeType == typeof(AuthorizeAttribute)))
            //    {
            //        bool controllerMarkToShow = false;

            //        object[] policyAtts = item.GetCustomAttributes(typeof(AuthorizeAttribute), true);
            //        if (item.CustomAttributes.Any(c => c.AttributeType == typeof(MarkedToNavBarAttribute)))
            //        {
            //            persianControllerAccessname = item.GetCustomAttribute<MarkedToNavBarAttribute>().name;
            //            controllerMarkToShow = true;
            //        }

            //        foreach (AuthorizeAttribute attItem in policyAtts)
            //        {
            //            var policyName = attItem.Policy;
            //            if (!claimsList.Any(c => c.Type == "AccessLevel" && c.Value == policyName))
            //            {
            //                checkControllerPolicy = false;
            //            }
            //            else
            //            {
            //                if (controllerMarkToShow)
            //                {
            //                    accessLevel.Add(new NavBarViewModel()
            //                    {
            //                        ActionName = "",
            //                        ControllerName = item.Name.Remove(item.Name.Length - 10),
            //                        PersianAccessLevelName = persianControllerAccessname
            //                    });
            //                }

            //            }
            //        }

            //    }

            //    if (checkControllerPolicy)
            //    {

            //        var methodInfos = item.GetMethods().Where(x => x.CustomAttributes
            //                                                    .Any(c => c.AttributeType == typeof(MarkedToNavBarAttribute)));
            //        foreach (var methodItem in methodInfos)
            //        {
            //            bool methodMarkToShow = false;
            //            string PersianMethodAccessName = "";
            //            if (methodItem.CustomAttributes.Any(x => x.AttributeType == typeof(MarkedToNavBarAttribute)))
            //            {
            //                PersianMethodAccessName = methodItem.GetCustomAttribute<MarkedToNavBarAttribute>().name;
            //                methodMarkToShow = true;
            //            }
            //            if (methodMarkToShow)
            //            {
            //                object[] methodAtts = methodItem.GetCustomAttributes(typeof(AuthorizeAttribute), true);
            //                if (methodAtts == null || methodAtts.Length == 0)
            //                {

IdentityLearning/Views/Shared/ActivateAccount.cshtml
    <div class="row gutters">
        <div class="alert alert-danger col-12">
            <p>حساب کاربری شما غیر فعال شده است.</p>

        </div>
    </div>

IdentityLearning/Views/Shared/EmailConfirm.cshtml
@{
    ViewData["Title"] = "EmailConfirm";
   
}
<div class="row gutters">

    <div class="col-12" style="margin-top:50px;text-align:center;direction:rtl;font-size:16px;font-weight:400">
        <p>ایمیلی حاوی تایید نامه برای ایمیل وارد شده شما ارسال شده است.</p>
        <p>لطفا از طریق لینک ارسالی برای ایمیلتان ، حساب کاربری خود را فعال کنید.</p>
    </div>
</div>

IdentityLearning/Views/Shared/_AdminPanelLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Bootstrap css -->
    <link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Icomoon Font Icons css -->
    <link rel="stylesheet" href="/fonts/style.css">

    <!-- Main css -->
    <link rel="stylesheet" href="/css/main.css">


    <!-- *************
        ************ Vendor Css Files *************
    ************ -->
    <!-- DateRange css -->
    <link rel="stylesheet" href="/vendor/daterange/daterange.css" />

    <!-- Chartist css -->
    <link rel="stylesheet" href="/vendor/chartist/css/chartist.min.css" />
    <link rel="stylesheet" href="/vendor/chartist/css/chartist-custom.css" />
</head>
<body>
    <style>
        .validation {
            color: red;
            font-size: 14px;
            font-weight: 300;
        }
    </style>

    <!-- Loading starts -->
    @*<div id="loading-wrapper">
            <div class="spinner-border" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>*@
    <!-- Loading ends -->
    <!-- *************
        ************ Header section start *************
    ************* -->
    <!-- Header start -->
    <header class="header">
        <div class="logo-wrapper">
            <a href="index.html" class="logo">
                <img src="img/logo.png" alt="Wafi Admin Dashboard" />
            </a>
            @*<a href="#" class="quick-links-btn" data-toggle="tooltip" data-placement="right" title="" data-original-title="Quick Links">
                    <i class="icon-menu1"></i>
                </a>*@
        </div>
        <div class="header-items">
            <!-- Custom search start -->
            <div class="custom-search">
                <input type="text" class="search-query" placeholder="Search here ...">
                <i class="icon-search1"></i>
            </div>
            <!-- Custom search end -->
            <!-- Header actions start -->
            <ul class="header-actions">

                <li class="dropdown">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a href="#" id="userSettings" class="user-settings" data-toggle="dropdown" aria-haspopup="true">

                            <span class="user-name">@User.FindFirst("UserName")?.Value</span>
                            <span class="avatar">
                                @if (User.FindFirst("ProfilePicture") == null)
                                {
                                    <img src="/img/img10.jpg" alt="Admin Template" />
                                }
                                else
                                {
                                    <img src="/images/profiles/@User.FindFirst("ProfilePicture").Value" alt="Admin Template" />
                                }

                                <span class="status busy"></span>
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userSettings">
                            <div class="header-profile-actions">
                                <div class="header-user-profile">
                                    <div class="header-user">
                                        @if (User.FindFirst("ProfilePicture") == null)
                                        {
                                            <img src="/img/img10.jpg" alt="Admin Template" />
                                        }
                                        else
                                        {
                                            <img src="/images/profiles/@User.FindFirst("ProfilePicture").Value" alt="Admin Template" />
                                        }



                                    </div>
                                    <h5>@User.FindFirst("UserName")?.Value</h5>
                                    <p>@User.FindFirst(ClaimTypes.Role)?.Value</p>
                                </div>
                                <a asp-action="EditProfile" asp-controller="Account"><i class="icon-user1"></i>ویرایش مشخصات من</a>
                                <a asp-action="ChangePassword" asp-controller="Account"><i class="icon-settings1"></i> تغییر رمز عبور</a>
                                <a asp-action="Login" asp-controller="Account"><i class="icon-settings1"></i> ورود با حساب کاربری دیگر</a>
                                <a asp-action="LogOut" asp-controller="Account"><i class="icon-log-out1"></i> خروج</a>
                            </div>
                        </div>
                    }
                    else
                    {
                        <a asp-action="login" asp-controller="account"
                           class="btn btn-danger">ورود</a>
                    }
                </li>
                @*<li>
                        <a href="#" class="quick-settings-btn" data-toggle="tooltip" data-placement="left" title="" data-original-title="Quick Settings">
                            <i class="icon-list"></i>
                        </a>
                    </li>*@
            </ul>
            <!-- Header actions end -->
        </div>
    </header>
    <!-- Header end -->
    <!-- Screen overlay start -->
    @*<div class="screen-overlay"></div>*@
    <!-- Screen overlay end -->
    <!-- Quicklinks box start -->
    @*<div class="quick-links-box">
            <div class="quick-links-header">
                بخش بندی ها
                <a href="#" class="quick-links-box-close">
                    <i class="icon-circle-with-cross"></i>
                </a>
            </div>

            @await Component.InvokeAsync("NavBar")


        </div>*@
    <!-- Quicklinks box end -->
    <!-- Quick settings start -->
    <!-- Quick settings end -->
    <!-- *************
        ************ Header section end *************
    ************* -->
    <!-- Container fluid start -->



    <div class="container-fluid">

        @if (User.Identity.IsAuthenticated)
        {
            <nav class="navbar navbar-expand-lg custom-navbar">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#WafiAdminNavbar" aria-controls="WafiAdminNavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i></i>
                        <i></i>
                        <i></i>
                    </span>
                </button>
                @await Component.InvokeAsync("TopMenu")

            </nav>


        }
















        <div class="main-container">
            <div class="content-wrapper">
                @RenderBody()
            </div>

        </div>

    </div>


    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.bundle.min.js"></script>
    <script src="/js/moment.js"></script>

    <script src="/vendor/slimscroll/slimscroll.min.js"></script>
    <script src="/vendor/slimscroll/custom-scrollbar.js"></script>

    <!-- Daterange -->
    <script src="/vendor/daterange/daterange.js"></script>
    <script src="/vendor/daterange/custom-daterange.js"></script>

    <!-- Chartist JS -->
    <script src="/vendor/chartist/js/chartist.min.js"></script>
    <script src="/vendor/chartist/js/chartist-tooltip.js"></script>
    <script src="/vendor/chartist/js/custom/threshold/threshold.js"></script>
    <script src="/vendor/chartist/js/custom/bar/bar-chart-orders.js"></script>

    <!-- jVector Maps -->
    <script src="/vendor/jvectormap/jquery-jvectormap-2.0.3.min.js"></script>
    <script src="/vendor/jvectormap/world-mill-en.js"></script>
    <script src="/vendor/jvectormap/gdp-data.js"></script>
    <script src="/vendor/jvectormap/custom/world-map-markers2.js"></script>

    <!-- Rating JS -->
    <script src="/vendor/rating/raty.js"></script>
    <script src="/vendor/rating/raty-custom.js"></script>

    <!-- Main Js Required -->
    <script src="/js/main.js"></script>


    <script src="vendor/apex/apexcharts.min.js"></script>

    @RenderSection("scripts", false)
</body>
</html>

IdentityLearning/Views/Shared/_BrowserGraph.cshtml
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">


        <div class="card"  style="height:400px;">
            <div class="card-header">
                <div class="card-title">آمار بازدید کاربران بر اساس مرورگر ها در یک ماه گذشته</div>
            </div>
            <div class="card-body">
                <div id="basic-donut-graph-monochrome-gradient" style="min-height: 289.992px;">
                   
                </div>
                <div class="resize-triggers"><div class="expand-trigger"><div style="width: 904px; height: 331px;"></div></div><div class="contract-trigger"></div></div>
            </div>
        </div>

    </div>

IdentityLearning/Views/Shared/_DeviceGraph.cshtml
<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12"  >
    <div class="card" style="height:400px;">
        <div class="card-header">
            <div class="card-title">برترین دستگاه های مورد استفاده کاربران در یک ماه گذشته</div>
        </div>
        <div class="card-body">
            <div id="donutColors" class="chart-height"> </div>
        </div>
    </div>

</div>

IdentityLearning/Views/Shared/_LastWeekGraph.cshtml
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="card">
        <div class="card-header">
            <div class="card-title">تعداد بازدید کاربران در هفته گذشته</div>
        </div>
        <div class="card-body">
            <div id="basic-area-graph"></div>
            <div class="resize-triggers">
                <div class="expand-trigger">
                    <div style="width: 1824px; height: 356px;">
                    </div>
                </div>
                <div class="contract-trigger">
                </div>
            </div>
        </div>
    </div>
</div>

IdentityLearning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/twitter-bootstrap/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/twitter-bootstrap/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body>
    <div class="header">


        <div class="header" style="direction:rtl;text-align:right;">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="#">منوی کاربری</a>

                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    <ul class="navbar-nav  mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="index" asp-controller="home">خانه </a>

                        </li>



                        @if (User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a class="nav-link" asp-action="logout" asp-controller="account">خروج</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-action="login" asp-controller="account">ورود</a>
                            </li>
                        }

                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </div>




    </div>


    <div class="row">

        <div class="container col-8" style="margin-top:30px;">
            @RenderBody()
        </div>

        @if (User.Identity.IsAuthenticated)
        {
            <div class="col-2">

                @await Component.InvokeAsync("NavBar")

            </div>
        }


    </div>
   
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.js"></script>
    @RenderSection("scripts", false)

    <script>
        var toggler = document.getElementsByClassName("caret");
        var i;

        for (i = 0; i < toggler.length; i++) {
            toggler[i].addEventListener("click", function () {
                this.parentElement.querySelector(".nested").classList.toggle("active");
                this.classList.toggle("caret-down");
            });
        }


    </script>
</body>
</html>