IdentityLearning/Controllers/UserManagerController.cs
using AutoMapper;
using Filters;
using IdentityLearning.Infrastructure;
using IdentityLearning.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SharedServices.Models.IdentityModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityLearning.Controllers
{
    [Authorize(Policy = nameof(PersmissionsEnum.BasePermission))]
    public class UserManagerController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly IMapper mapper;

        public UserManagerController(UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager, IMapper mapper)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.mapper = mapper;
        }



        [Authorize(Policy = nameof(PersmissionsEnum.UserView))]
        [MarkedToNavBar("نمایش کاربران")]
        public async Task<IActionResult> UsersView()
        {
            if (TempData.ContainsKey("DeleteSucc"))
            {
                TempData.Remove("DeleteSucc");
                ViewData["DeleteSucc"] = true;
            }
            else if (TempData.ContainsKey("DeleteError"))
            {
                TempData.Remove("DeleteError");
                ViewData["DeleteError"] = true;
            }

            var superUserId = (await userManager.GetUsersInRoleAsync("SuperAdmin")).First();
            var users = mapper.Map<List<UserListViewModel>>
                            (userManager.Users.Where(c => c.UserName != User.Identity.Name
                           && c.Id != superUserId.Id).ToList());

            return View(users);
        }

        [ValidateAntiForgeryToken]
        [Authorize(Policy = nameof(PersmissionsEnum.DeleteUser))]
        [ServiceFilter(typeof(IsUserExistFilter))]

        public async Task<IActionResult> DeleteUser(string id)
        {
            id = CheckXss.CheckIt(id);
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(id);
                await userManager.DeleteAsync(user);
                TempData["DeleteSucc"] = true;
            }
            else
            {
                TempData["DeleteError"] = true;
            }

            return RedirectToAction(nameof(UsersView));
        }


        [Authorize(Policy = nameof(PersmissionsEnum.UpdateUser))]
        [ServiceFilter(typeof(IsUserExistFilter))]
        public async Task<IActionResult> UpdateUser(string id)
        {
            id = CheckXss.CheckIt(id);
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(id);
                UserUpdateViewModel up = new UserUpdateViewModel()
                {
                    AboutMe = user.AboutMe,
                    PersianName = user.PersianName,
                    Email = user.Email,
                    Id = user.Id,
                    PhoneNumber = user.PhoneNumber
                };
                return View(up);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = nameof(PersmissionsEnum.UpdateUser))]
        [ServiceFilter(typeof(IsUserExistFilter))]
        public async Task<IActionResult> UpdateUser(UserUpdateViewModel userUpdate)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(userUpdate.Id);
                bool result = false;
                bool isEmailNew = userUpdate.Email.ToLower() != user.Email;
                if (isEmailNew)
                {
                    result = userManager.Users.Any(x => x.Email.ToLower() == userUpdate.Email.ToLower()
                                       || x.UserName.ToLower() == userUpdate.Email.ToLower());

                }

                if (result == false)
                {

                    user.AboutMe = userUpdate.AboutMe;
                    user.PersianName = userUpdate.PersianName;
                    user.PhoneNumber = userUpdate.PhoneNumber;
                    if (isEmailNew)
                    {
                        user.Email = userUpdate.Email;
                        user.UserName = userUpdate.Email;
                    }
                    var updateResult = await userManager.UpdateAsync(user);
                    if (updateResult.Succeeded == false)
                    {
                        ModelState.AddModelError("errorInProcess", "سیستم با مشکل مواجه شده است");
                        return View(userUpdate);
                    }
                }
                else
                {
                    ModelState.AddModelError("EmailIsDuplicated", "ایمیل وارد شده تکراری است");
                    return View(userUpdate);
                }
                return RedirectToAction(nameof(UsersView));
            }

            return View(userUpdate);

        }


        [Authorize(Policy = nameof(PersmissionsEnum.SetRoleTOUser))]
        [ServiceFilter(typeof(IsUserExistFilter))]
        public async Task<IActionResult> AccessLevelUser(string id)
        {
            id = CheckXss.CheckIt(id);
            if (ModelState.IsValid)
            {
                if (TempData["Success"] != null)
                {
                    TempData.Remove("Success");
                    ViewBag.Success = true;
                }
                var roles = roleManager.Roles.ToList();
                var user = await userManager.FindByIdAsync(id);
                var userRolenames = await userManager.GetRolesAsync(user);
                var userRoles = roleManager.Roles.Where(x => userRolenames.Any(y => y == x.Name)).ToList();
                UserToRoleViewModel uv = new UserToRoleViewModel();
                uv.UserId = user.Id;
                uv.UserName = user.PersianName;

                foreach (var item in userRoles)
                {
                    uv.RoleIn.Add(new SelectListItem()
                    {
                        Selected = true,
                        Value = item.Id,
                        Text = item.Name
                    });
                }

                foreach (var item in roles.Except(userRoles).ToList())
                {
                    uv.RoleOut.Add(new SelectListItem()
                    {
                        Selected = false,
                        Text = item.Name,
                        Value = item.Id
                    });
                }

                return View(uv);

            }
            return NotFound();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize(Policy = nameof(PersmissionsEnum.SetRoleTOUser))]
        public async Task<IActionResult> AccessLevelUser(UserToRoleViewModel uv)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(uv.UserId);
                if (user == null)
                {
                    ModelState.AddModelError("IdNotValid", "چنین کاربری در سیستم موجود نیست");
                    ViewBag.UnValid = true;
                    return View(uv);
                }
                var roleMustRemove = new List<string>();
                foreach (var item in uv.RoleIn)
                {
                    if (!item.Selected)
                        roleMustRemove.Add(item.Text);
                }

                var roleMustAdd = new List<string>();
                foreach (var item in uv.RoleOut)
                {
                    if (item.Selected)
                        roleMustAdd.Add(item.Text);
                }


                var addResult = await userManager.AddToRolesAsync(user, roleMustAdd);
                var subresult = await userManager.RemoveFromRolesAsync(user, roleMustRemove);

                if (!addResult.Succeeded || !subresult.Succeeded)
                {
                    ModelState.AddModelError("errorInProcess", "پردازش این عملیات با مشکل مواجه شده است");
                    ViewBag.UnValid = true;
                    return View(uv);
                }
                TempData["Success"] = true;
                return RedirectToAction("AccessLevelUser", new[] { uv.UserId });
            }
            ViewBag.UnValid = true;
            return View(uv);

        }
    }
}

IdentityLearning/Views/UserManager/AccessLevelUser.cshtml
@model UserToRoleViewModel

@{
    ViewData["Title"] = "AccessLevelUser";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}




<h4 style="margin-bottom:20px;text-align:right;direction:rtl">نقش های کاربر @Model.UserName</h4>

<div class="row gutters" style="font-size:16px;">
    @if (ViewBag.UnValid != null)
    {
        <div asp-validation-summary="All"
             class="alert alert-danger col-12" style="direction:rtl;text-align:right;"></div>
    }

    @if (ViewBag.Success != null)
    {
        <div class="col-12 alert alert-success"
             style="direction:rtl;text-align:right;">
            <p>
                عملیات با موفقیت انجام شد
            </p>
        </div>
    }


    <form class="col-12" asp-action="AccessLevelUser" asp-controller="UserManager" method="post" asp-antiforgery="true">

        <input asp-for="UserId" value="@Model.UserId" hidden />


        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="table-container">
                <div class="table-responsive">

                    <table class="table custom-table m-0 " style="direction:rtl;text-align:right;">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th>نام نقش</th>
                                <th> تخصیص یا عدم تخصیص نقش به کاربر</th>
                            </tr>
                        </thead>

                        <tbody>
                            @{ int counter = 1;}
                            @for (int i = 0; i < Model.RoleOut.Count; i++)
                            {
                                <tr>
                                    <th scope="row">@(counter)</th>
                                    <td>@Model.RoleOut[i].Text</td>
                                    <td>
                                        <input type="checkbox" asp-for="RoleOut[i].Selected" />
                                        <input type="hidden" asp-for="RoleOut[i].Value" hidden />
                                        <input type="hidden" asp-for="RoleOut[i].Text" hidden />
                                    </td>
                                </tr>


                                counter++;

                            }

                            @for (int i = 0; i < Model.RoleIn.Count; i++)
                            {
                                <tr>
                                    <th scope="row">@counter</th>
                                    <td>@Model.RoleIn[i].Text</td>
                                    <td>
                                        <input type="checkbox" asp-for="RoleIn[i].Selected" />
                                        <input type="hidden" asp-for="RoleIn[i].Value" hidden />
                                        <input type="hidden" asp-for="RoleIn[i].Text" hidden />
                                    </td>
                                </tr>

                                counter++;

                            }


                        </tbody>
                    </table>
                </div>
            </div>
        </div>



      

        <div class="row">
            <div class="col-2">
                <input type="submit" class="btn btn-success btn-block" value="ثبت" style="float:right;margin-top:20px;min-width:120px;" />

            </div>
        </div>

    </form>


    <div class="col-12">
        <a class="btn btn-danger" style="float:left;width:130px;" asp-action="UsersView" asp-controller="UserManager">بازگشت به صفحه قبل</a>

    </div>
</div>

IdentityLearning/Views/UserManager/UpdateUser.cshtml
@model UserUpdateViewModel
@{
    ViewData["Title"] = "UpdateUser";
    // Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    label {
        font-size: 16px;
        font-weight: 400;
    }
</style>

<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="card">
        <div class="card-body">

            <div class="row gutters">
                <form asp-action="UpdateUser" asp-controller="UserManager"
                      asp-antiforgery="true"
                      method="post"
                      class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="col-12" asp-validation-summary="ModelOnly">

                    </div>
                    <input asp-for="@Model.Id" hidden />



                    <div class="col-xl-4 col-lg col-md-6 col-sm-8 col-12">
                        <label asp-for="@Model.Email"></label>
                        <input class="form-control" type="text" asp-for="@Model.Email" placeholder="ایمیل را وارد کنید" />
                        <span asp-validation-for="Email" class="validation"></span>

                    </div>

                    <div class="col-xl-4 col-lg col-md-6 col-sm-8 col-12">
                        <label asp-for="@Model.AboutMe"></label>
                        <textarea class="form-control" type="text" asp-for="@Model.AboutMe" placeholder="متنی درباره خودتان وارد کنید" ></textarea>
                        <span asp-validation-for="AboutMe" class="validation"></span>
                    </div>

                    <div class="col-xl-4 col-lg col-md-6 col-sm-8 col-12">
                        <label asp-for="@Model.PersianName"></label>
                        <input class="form-control" type="text" asp-for="@Model.PersianName" placeholder="نام کاربری برای خود وارد کنید" />
                        <span asp-validation-for="PersianName" class="validation"></span>
                    </div>

                    <div class="col-xl-4 col-lg col-md-6 col-sm-8 col-12">
                        <label asp-for="@Model.PhoneNumber"></label>
                        <input class="form-control" type="text" asp-for="@Model.PhoneNumber" placeholder="شماره موبایل خود را وارد کنید" />
                        <span asp-validation-for="PhoneNumber" class="validation"></span>
                    </div>


                    <div class="col-xl-4 col-lg col-md-6 col-sm-8 col-12">
                        <input style="margin-top:40px;" class="btn btn-success btn-block" type="submit" value="ثبت" />
                    </div>

                </form>

                <div class="col-12" style="margin-top:30px;">
                    <a asp-action="UsersView" asp-controller="UserManager" class="btn btn-primary" style="float:left;width:100px;">بازگشت به عقب</a>
                </div>
            </div>
        </div>
    </div>
</div>

IdentityLearning/Views/UserManager/UsersView.cshtml
@model List<UserListViewModel>
@{
    ViewData["Title"] = "UsersView";
    // Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>کاربران سایت</h1>
<div class="row gutters">
    @if (ViewData["DeleteError"] != null && (bool)ViewData["DeleteError"] == true)
    {
        <div class="col-12">
            <div asp-validation-summary="All">

            </div>
        </div>

    }

    @if (ViewData["DeleteSucc"] != null && (bool)ViewData["DeleteSucc"] == true)
    {
        <div class="alert alert-success">
            حذف با موفقیت انجام شد
        </div>
    }


    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="table-container">
            <div class="table-responsive">

                <table class="table custom-table m-0" style="direction:rtl;font-size:16px;">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">نام کاربری</th>
                            <th scope="col">حذف کاربر</th>
                            <th scope="col">تغییرات در کاربر</th>
                            <th scope="col">اعمال سطح دسترسی به کاربر</th>
                            <th scope="col">وضعیت کاربر</th>
                            <th scope="col">وضعیت فعال بودن ایمیل کاربر</th>

                        </tr>
                    </thead>
                    @{
                        int counter = 1;
                    }
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@counter</th>
                                <td>@item.UserName</td>
                                <td>
                                    <form asp-action="DeleteUser" asp-controller="UserManager" asp-antiforgery="true"
                                          asp-route-id="@item.Id"
                                          method="post">
                                        <input type="submit" class="btn btn-danger"
                                               value="حذف کاربر" />


                                    </form>

                                </td>
                                <td>

                                    <form asp-action="UpdateUser" asp-controller="UserManager"
                                          asp-route-id="@item.Id"
                                          method="get">
                                        <input type="submit" class="btn btn-info"
                                               value=" تغییر در اطلاعات کاربر" />


                                    </form>

                                </td>

                                <td>
                                    <form asp-action="AccessLevelUser" asp-controller="UserManager"
                                          asp-route-id="@item.Id"
                                          method="get">
                                        <input type="submit" class="btn btn-warning"
                                               value="  تغییر سطح دسترسی کاربر" />


                                    </form>

                                </td>
                                <td>
                                    @if (item.IsActive)
                                    {
                                        <span style="cursor:pointer" id="@item.Id" class="badge badge-success" onclick="ChangeUserStatus(event)">فعال</span>
                                    }
                                    else
                                    {
                                        <span style="cursor:pointer" id="@item.Id" class="badge badge-danger" onclick="ChangeUserStatus(event)">غیر فعال</span>
                                    }
                                </td>
                                <td>
                                    @if (item.EmailConfirmed)
                                    {
                                        <span class="badge badge-success">تایید شده</span>
                                    }
                                    else
                                    {
                                        <span class="badge badge-danger">تایید نشده</span>
                                    }
                                </td>
                            </tr>

                            counter++;
                        }
                    </tbody>
                </table>


            </div>

        </div>

    </div>



</div>


@section scripts{

    <script>
        function ChangeUserStatus(e) {
             $.ajax({
            type: "POST",
            url: '@Url.Action("ChangeUserActivate","Account")', // Replace YOUR_CUSTOM_HANDLER with your handler.
            contentType: "application/json; charset=utf-8",
                 dataType: "json",
                 data: JSON.stringify(e.target.id)
             }).done(function (data) {
                 if (data == "success") {
                     if ($("#" + e.target.id).hasClass("badge-success")) {
                         $("#" + e.target.id).removeClass("badge-success");
                         $("#" + e.target.id).addClass("badge-danger");
                          $("#" + e.target.id).text("غیر فعال");
                     } else {
                         $("#" + e.target.id).removeClass("badge-danger");
                         $("#" + e.target.id).addClass("badge-success");
                         $("#" + e.target.id).text("فعال");
                     }
                 }
        });

        }


    </script>

}